# data information

name: datasets
datapath:  ./datasets/     # path to dataset


# training information
niter: 200
cuda: true
outf: ./checkpoints/
outf_test: ./checkpoints/test/

# GAN parameters
branch: 3                 # stacked architecture: 64--->128--->256[3]
z_dim: 100                # the dim of noise
c_dim: 512                # the encoded z dim
ngf: 64
ndf: 64
use_z: true               # using noise for Image generation
num_residual: 2
