name: facades            # the name of the training data sets
dataPath: /media/scw4750/dataset/image-translation/facades
loadSize: 286            # loading size of image
fineSize: 256            # fineSize
flip: 1

cuda: true
AtoB: BtoA               # which direction: AtoB is semantic map to real
outf: checkpoints        # where to collect the log
batchSize: 1
input_nc: 3
output_nc: 3
box_width: 64            # box width
nepoch: 200
lr: 0.0002
beta1: 0.5
n_step: 1
region_width: 64

# network setting
gan_type: CGAN
netG: resnet
ngf: 64
netD: patchd
ndf: 64
reviser: imaged

# proposal
mask_operation: true
window_width: 1
window_height: 1
region_width: 70
region_height: 70